[workspace]
authors = ["Alex-dt <alexanderbaekey@gmail.com>"]
channels = ["conda-forge"]
name = "ioc-hkl"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = "2.3.4.*"
pandas = ">=2.3.3,<3"
scipy = ">=1.16.3,<2"
matplotlib = ">=3.10.7,<4"
tqdm = ">=4.67.1,<5"
pygobject = ">=3.54.5,<4"
hkl = ">=5.1.2.3679,<6"
